suite: Controller Additional Existing Secrets
release:
  name: my-release
  namespace: my-namespace
templates:
  - jenkins-controller-statefulset.yaml
  - config.yaml
tests:
  - it: test additional existing secrets StatefulSet
    template:  jenkins-controller-statefulset.yaml
    set:
      controller.additionalExistingSecrets:
        - name: secret-name-1
          keyName: username
        - name: secret-name-1
          keyName: password
    asserts:
      - isKind:
          of: StatefulSet
      - equal:
          path: spec.template.spec.containers[0].volumeMounts[6]
          value:
            mountPath: /run/secrets/secret-name-1-username
            name: secret-name-1-username
            readOnly: true
            subPath: username
      - equal:
          path: spec.template.spec.containers[0].volumeMounts[7]
          value:
            mountPath: /run/secrets/secret-name-1-password
            name: secret-name-1-password
            readOnly: true
            subPath: password
      - equal:
          path: spec.template.spec.volumes[3]
          value:
            name: secret-name-1-username
            secret:
              secretName: secret-name-1
      - equal:
          path: spec.template.spec.volumes[4]
          value:
            name: secret-name-1-password
            secret:
              secretName: secret-name-1
