suite: Controller Additional Existing Secrets
release:
  name: my-release
  namespace: my-namespace
templates:
  - jenkins-controller-statefulset.yaml
  - config.yaml
tests:
  - it: test additional existing secrets StatefulSet
    template: jenkins-controller-statefulset.yaml
    set:
      controller.additionalExistingSecrets:
        - name: secret-name-1
          keyName: username
        - name: secret-name-1
          keyName: password
    asserts:
      - isKind:
          of: StatefulSet
      - equal:
          path: spec.template.spec.containers[0].volumeMounts[6]
          value:
            mountPath: /run/secrets/
            name: jenkins-additional-secrets
            readOnly: true
      - equal:
          path: spec.template.spec.volumes[3]
          value:
            name: jenkins-additional-secrets
            projected:
              sources:
                - secret:
                    name: secret-name-1
                    items:
                      - key: username
                        path: username
                - secret:
                    name: secret-name-1
                    items:
                      - key: password
                        path: password
