{{- if .Values.controller.httpRoute.enabled }}
{{- $root := . }}
{{- $hostnames := (list) }}
{{- if .Values.controller.httpRoute.ingressCompact }}
  {{- if .Values.controller.ingress.hostName }}
    {{- $hostnames = append $hostnames .Values.controller.ingress.hostName }}
  {{- end }}
  {{- if .Values.controller.ingress.resourceRootUrl }}
     {{- $hostnames = append $hostnames .Values.controller.ingress.resourceRootUrl }}
  {{- end }}
{{- else }}
  {{- $hostnames = default (list) .Values.controller.httpRoute.hostnames }}
{{- end }}
---
apiVersion: {{ .Values.controller.httpRoute.apiVersion }}
kind: {{ .Values.controller.httpRoute.kind }}
metadata:
  name: {{ include "jenkins.fullname" . }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: {{ .Values.controller.httpRoute.gatewayRef.name }}
    namespace: {{ .Values.controller.httpRoute.gatewayRef.namespace }}
  hostnames:
  {{- range $hostnames }}
    - {{ . | quote }}
  {{- end }}
  rules:
{{- range $rule := (default (list) $root.Values.controller.httpRoute.extraPaths) }}
  - {{ tpl (toYaml $rule) $root | nindent 4 }}
{{- end }}
  - backendRefs:
    - name: {{ include "jenkins.fullname" $root }}
      port: {{ $root.Values.controller.servicePort }}
{{- end }}